version: "3"
services:
  react-app:
    image: react-client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: node-server
    env_file: ./backend/config.env
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
