version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:80
    links:
      - backend
  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - MONGO_URL=mongo
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
